spelling - #29

diff --git a/.github/workflows/rotate.yml b/.github/workflows/rotate.yml
--- a/.github/workflows/rotate.yml
+++ b/.github/workflows/rotate.yml
@@ -1,8 +1,9 @@
-name: Rotate  (Dispatch Trigger)
+name: Rotate  (lock manifest)
 
 on:
   workflow_call:
     inputs:
+      # Required  
       repo:
         description: 'Repo to rotate (owner/repo)'
         required: true
@@ -31,27 +32,26 @@ on:
         description: 'Git user email for the merge commit'
         required: true
         type: string
+      
+      # Optional  
+
+      rotator_pin:
+        description: 'Pin the gh-rotator GitHub CLI extension to a specific version - default is not pinned (main/LATEST)'
+        required: false
+        type: string
+        default: ''
         
     secrets:
       token:
         required: true
         description: 'A PAT with content:write permissions to update the manifest'
 
-
-# Add this permissions block
-permissions:
-  contents: write  # This grants write access to repository contents
-
-
 jobs:
   lock-manifest:
     runs-on: ubuntu-latest
-    outputs:
-      CONFIGURATION: ${{ steps.set_config.outputs.CONFIGURATION }}
-      COMPONENT_REPO: ${{ steps.set_config.outputs.COMPONENT_REPO }}
-      COMPONENT_EVENT_TYPE: ${{ steps.set_config.outputs.COMPONENT_EVENT_TYPE }}
-      COMPONENT_EVENT_NAME: ${{ steps.set_config.outputs.COMPONENT_EVENT_NAME }}
-      COMPONENT_SHA: ${{ steps.set_config.outputs.COMPONENT_SHA }}
+    permissions:
+      contents: write
+
     steps:
       - name: Checkout the repository
         uses: actions/checkout@v4       
@@ -72,17 +72,28 @@ jobs:
         # assume python3 is installed, it is in ubuntu-latest, 
         # but if you are using a different image, you may need to install it
         run: |
-          command -v python3 || { echo "Python3 is not installed"; exit 1; }
+          if command -v python3 &> /dev/null; then
+            PYTHON_VERSION=$(python3 --version)
+            echo "Using Python version: $PYTHON_VERSION" >> $GITHUB_STEP_SUMMARY
+          else
+            echo "ERROR: Python3 is not installed" >> $GITHUB_STEP_SUMMARY
+            exit 1
+          fi
 
-      - name: Install gh extension 'thetechcollective/rotator'
+      - name: Install gh extension 'thetechcollective/gh-rotator'
         # Visit https://github.com/thetechcollective/gh-rotator for more information
         env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} #standard token is fine for installing the extension
         run: |
-          gh extension install thetechcollective/gh-rotator
+          if [[ -n "${{ inputs.rotator_pin }}" ]]; then
+            gh extension install thetechcollective/gh-rotator --pin ${{ inputs.rotator_pin }}
+            echo "Installed thetechcollective/gh-rotator pinned to: ${{ inputs.rotator_pin }}" >> $GITHUB_STEP_SUMMARY
+          else
+            gh extension install thetechcollective/gh-rotator
+            echo "Installed thetechcollective/gh-rotator from main/LATEST" >> $GITHUB_STEP_SUMMARY
+          fi
 
-      - name: Receive and Use Trigger Data from Inputs
-        id: set_config
+      - name: Determine configuration and lock manifest
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
@@ -91,75 +102,25 @@ jobs:
           echo "Triggering commit was: [**\`${{ inputs.sha }}\`**](https://github.com/${{ inputs.repo }}/commit/${{ inputs.sha }})" >> $GITHUB_STEP_SUMMARY
 
           # Set env vars from inputs and also set them as outputs
-          echo "COMPONENT_REPO=${{ inputs.repo }}" >> $GITHUB_ENV
-          echo "COMPONENT_REPO=${{ inputs.repo }}" >> $GITHUB_OUTPUT
-          echo "COMPONENT_EVENT_TYPE=${{ inputs.event_type }}" >> $GITHUB_ENV
-          echo "COMPONENT_EVENT_TYPE=${{ inputs.event_type }}" >> $GITHUB_OUTPUT
-          echo "COMPONENT_EVENT_NAME=${{ inputs.event_name }}" >> $GITHUB_ENV
-          echo "COMPONENT_EVENT_NAME=${{ inputs.event_name }}" >> $GITHUB_OUTPUT
           echo "COMPONENT_SHA=${{ inputs.sha }}" >> $GITHUB_ENV
           echo "COMPONENT_SHA=${{ inputs.sha }}" >> $GITHUB_OUTPUT
 
           CONFIGURATION=$(gh rotator config --repo ${{ inputs.repo }} --event-type ${{ inputs.event_type }} --event-name ${{ inputs.event_name }})
-          echo "CONFIGURATION=$CONFIGURATION" >> $GITHUB_OUTPUT
+          echo "Configuration to update: $CONFIGURATION" >> $GITHUB_OUTPUT
           echo "CONFIGURATION=$CONFIGURATION" >> $GITHUB_ENV
 
           gh rotator lock --repo ${{ inputs.repo }} --event-type ${{ inputs.event_type }} --event-name ${{ inputs.event_name }} --sha ${{ inputs.sha }} --verbose
 
       - name: Commit and Push Manifest Changes
         env:
-          GITHUB_TOKEN: ${{ secrets.ROTATOR_COMMIT_TOKEN }}
+          GITHUB_TOKEN: ${{ secrets.token }}
         run: |
           git add -A
           git commit -m "Update manifest for ${{ inputs.repo }}
-            Triggering event was: '${{ env.COMPONENT_EVENT_TYPE }}:${{ env.COMPONENT_EVENT_NAME }}'
-            Triggering commit was was https://github.com/${{ env.COMPONENT_REPO }}/commit/${{ env.COMPONENT_SHA }} "
+            Triggering event was: '${{ inputs.event_type }}:${{ inputs.event_name }}'
+            Triggering commit was: https://github.com/${{ inputs.repo }}/commit/${{ inputs.sha }} 
+            Updated the manifest for the '${{ env.CONFIGURATION }}' configuration"
           git push origin main
 
-          echo "Successfully updated the manifest for the '${{ env.CONFIGURATION }}' configuration"  >> $GITHUB_STEP_SUMMARY
+          echo "Successfully updated and committed the manifest for the '${{ env.CONFIGURATION }}' configuration"  >> $GITHUB_STEP_SUMMARY
 
-  deploy-iac:
-    runs-on: ubuntu-latest
-    needs: lock-manifest
-    env:
-      CONFIGURATION: ${{ needs.lock-manifest.outputs.CONFIGURATION }}
-      COMPONENT_REPO: ${{ needs.lock-manifest.outputs.COMPONENT_REPO }}
-      COMPONENT_EVENT_TYPE: ${{ needs.lock-manifest.outputs.COMPONENT_EVENT_TYPE }}
-      COMPONENT_EVENT_NAME: ${{ needs.lock-manifest.outputs.COMPONENT_EVENT_NAME }}
-      COMPONENT_SHA: ${{ needs.lock-manifest.outputs.COMPONENT_SHA }}
-    steps:
-      - name: Checkout the repository
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-          ref: main
-
-      - name: Ensure Python
-        run: |
-          command -v python3 || { echo "Python3 is not installed"; exit 1; }
-
-      - name: Install gh extension 'thetechcollective/rotator'
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: |
-          gh extension install thetechcollective/gh-rotator
-
-      - name: Do Your Thing
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: |
-          echo "Deploying the manifest for '${{ env.CONFIGURATION }}' configuration"
-          echo "Triggering event was: '${{ env.COMPONENT_EVENT_TYPE }}:${{ env.COMPONENT_EVENT_NAME }}'"
-          echo "Triggering commit was was: [**\`${{ env.COMPONENT_SHA }}\`**](https://github.com/${{ env.COMPONENT_REPO }}/commit/${{ env.COMPONENT_SHA }})"
-
-          echo "Deploying the manifest for the '${{ env.CONFIGURATION }}' configuration"  >> $GITHUB_STEP_SUMMARY
-          echo "Triggering event was: '${{ env.COMPONENT_EVENT_TYPE }}:${{ env.COMPONENT_EVENT_NAME }}'"  >> $GITHUB_STEP_SUMMARY
-          echo "Triggering commit was was: [**\`${{ env.COMPONENT_SHA }}\`**](https://github.com/${{ env.COMPONENT_REPO }}/commit/${{ env.COMPONENT_SHA }})"  >> $GITHUB_STEP_SUMMARY
-
-
-          git pull
-          MANIFEST=$( gh rotator manifest --configuration ${{ env.CONFIGURATION }} )
-
-          echo '```json'       >> $GITHUB_STEP_SUMMARY
-          echo "$MANIFEST"     >> $GITHUB_STEP_SUMMARY
-          echo '```'           >> $GITHUB_STEP_SUMMARY
